# Generated by Django 3.2 on 2022-05-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='collection_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.collectiondays'),
        ),
    ]
