# Generated by Django 3.2 on 2022-05-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_order_collection_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collected_order',
            field=models.IntegerField(choices=[(0, 'Not Collected'), (1, 'Collected')], default=0),
        ),
    ]
