# Generated by Django 3.2 on 2022-04-02 14:00

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DishesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254, unique=True)),
                ('friendly_name', models.CharField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Dishes Categories',
            },
        ),
        migrations.CreateModel(
            name='WineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=254)),
                ('variety', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254, unique=True)),
                ('friendly_name', models.CharField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Wine Categories',
            },
        ),
        migrations.CreateModel(
            name='Wines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('slug_name', models.SlugField(max_length=254, unique=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.winecategory')),
            ],
            options={
                'verbose_name_plural': 'Wines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('slug_name', models.SlugField(max_length=254, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Frozen'), (1, 'Fresh')], default=1)),
                ('image', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.dishescategory')),
            ],
            options={
                'verbose_name_plural': 'Dishes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('slug_name', models.SlugField(max_length=254, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.dishes')),
                ('wine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.wines')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
